# Generated by Django 4.0 on 2022-01-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userweight',
            name='day',
            field=models.DateField(),
        ),
        migrations.AlterModelTable(
            name='userweight',
            table='userweight',
        ),
    ]
