# Generated by Django 4.0 on 2022-01-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_data', '0002_alter_userweight_day_alter_userweight_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userweight',
            table=None,
        ),
    ]
