# Generated by Django 4.0.1 on 2022-01-31 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_data', '0003_alter_userweight_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userweight',
            options={'managed': False},
        ),
    ]
