# Generated by Django 4.0 on 2022-01-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(verbose_name='Дата публикации')),
                ('user_id', models.IntegerField()),
                ('weight', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
    ]
